export const opinioesMedicos = [
  { titulo: "Atendimento ⭐⭐⭐⭐⭐", opiniao: "Dr. João foi super atencioso e explicou tudo direitinho! 👨‍⚕️👏" },
  { titulo: "Demorou demais 😡", opiniao: "Esperei mais de 1h pra ser atendido, falta de respeito! ⏳" },
  { titulo: "Consulta rápida ✅", opiniao: "Gostei da objetividade, sem enrolação! 😊" },
  { titulo: "Pouca empatia 😕", opiniao: "Achei o médico frio, parecia com pressa... 😔" },
  { titulo: "Excelente profissional 👏", opiniao: "Dra. Fernanda me ouviu com paciência e cuidado! 💙" },
  { titulo: "Preço alto 💸", opiniao: "Consulta boa, mas podia ser mais barata... 🥲" },
  { titulo: "Volto com certeza 👍", opiniao: "Atendimento humanizado, gostei muito! ❤️" },
  { titulo: "Recepção desorganizada 😠", opiniao: "Cheguei na hora e me chamaram atrasado. Falta organização!" },
  { titulo: "Recomendo 👌", opiniao: "Me passou confiança e explicou tudo detalhado. 🔍" },
  { titulo: "Falta de atenção 😑", opiniao: "Parecia que nem tava me ouvindo direito... 😕" },
  { titulo: "Ótimo retorno 📅", opiniao: "Voltei no retorno e resolveu meu problema. Gratidão! 🙏" },
  { titulo: "Exame desnecessário 🤷‍♂️", opiniao: "Achei que pediu exame que não precisava, só pra gastar... 💸" },
  { titulo: "Clínica limpa 🧼", opiniao: "Ambiente limpinho e organizado, adorei! ✨" },
  { titulo: "Muita espera 😤", opiniao: "Fila enorme, marquei horário à toa... 🕒" },
  { titulo: "Super profissional 👨‍⚕️", opiniao: "Atendimento nota 10, resolveu tudo. Recomendo! 💯" },
  { titulo: "Precisa melhorar 😬", opiniao: "Achei o consultório meio bagunçado, podia melhorar." },
  { titulo: "Equipe maravilhosa 💕", opiniao: "Secretária e médico super gentis, amei! 🌟" },
  { titulo: "Consulta corrida 🏃‍♂️", opiniao: "Parecia que tava correndo pra acabar logo... 🤨" },
  { titulo: "Melhor doutora! 👩‍⚕️", opiniao: "Dra. Carla é incrível, me deixou super tranquila. 🥰" },
  { titulo: "Experiência ruim 😣", opiniao: "Não me senti acolhido, não volto mais... 🚫" },
];
