services:
  medical:
    image: postgres:15
    container_name: medical
    restart: always
    environment:
      POSTGRES_USER: teuzo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medicaldb
    ports:
      - "5432:5432"
    volumes:
      - medical_data:/var/lib/postgresql/data

volumes:
  medical_data:
